<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.antmedia</groupId>
  <artifactId>media</artifactId>
  <version>2.11.3</version>
  <packaging>pom</packaging>
  <parent>
    <groupId>io.antmedia</groupId>
    <artifactId>parent</artifactId>
    <version>2.11.3</version>
    <relativePath>./ant-media-server-parent</relativePath>
  </parent>
  <modules>
    <module>ant-media-server-parent</module>
    <module>StreamApp</module>
    <module>seetaface6SDK</module>
    <module>ant-media-enterprise</module>
    <module>agrhub-media-parent</module>
    <module>agrhub-media-core</module>
    <module>Ant-Media-Server</module>
	<module>CamOS/webapp</module>
    <module>CloudyTV/webapp</module>
    <module>VidGen/webapp</module>
    <module>RealGIS/webapp</module>
  </modules>
</project>